spring:
  application:
    name: online-store
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/online-store
  jpa:
    database: postgresql
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
