CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(200),
                       surname VARCHAR(200),
                       email VARCHAR(200),
                       username VARCHAR NOT NULL UNIQUE,
                       password VARCHAR NOT NULL,
                       created_at TIMESTAMP,
                       balance NUMERIC,
                       role VARCHAR
);

CREATE TABLE Category (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR
);


CREATE TABLE Item (
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR,
                      description VARCHAR,
                      price NUMERIC,
                      category_id INT REFERENCES Category(id) ON DELETE CASCADE
);

CREATE TABLE Person_Item(
                            person_id INT REFERENCES Person(id) ON DELETE CASCADE,
                            item_id INT REFERENCES Item(id) ON DELETE CASCADE,
                            PRIMARY KEY (person_id, item_id)
);
